### ISSUE TITLE
List the existing modules (SHC, SHP) and their available commands 

### ISSUE THREAD

**Issue by jenniferasmar** [willyyhuang/soen-343#67]
In user profiles, you should list the existing modules (SHC, SHP) and their available commands and grant/deny permissions based on the user profile.  You need to specify if the permission depends on the location of the user profile or not.  For example, if the user is inside or outside the home

**Comment by willyyhuang** [comment]
how does permissions work, should they be determined from front end?

**Comment by jenniferasmar** [comment]
No, whenever someone tries to do something the backend verifies their role, if it was successful, then the boolean success is true otherwise there is two options: if boolean awayMode is false --> permission denied
if boolean awayMode is True --> awayMode is on and someone is trying to get in the house -->notification and call the cops after X time

Here is what front end receives when a call is made for Creating a user, change location, turn on/off Lights, block unblock doors and windows:
![image](https://user-images.githubusercontent.com/60263256/98305990-df7a0680-1f90-11eb-8cd7-1954a8e1523c.png)

**Comment by willyyhuang** [comment]
hmm should user creation have this as well? shouldn't that be admin priv instead

**Comment by jenniferasmar** [comment]
User creation is only to verify if away mode is on and you're trying to put a user in the house

**Comment by willyyhuang** [comment]
okay so all front end needs here is displaying like a notification based on backend response

**Comment by jenniferasmar** [comment]
Yes. Can you make a timer that shows another notification saying "Cops are on their way" after timeBeforeAuthorities amount of time? If it's too complicated then just show a message " Cops will be called in timeBeforeAuthorities  time."
